### ISSUE TITLE
[wish] make a new release

### ISSUE THREAD

**Issue by retokromer** [emericg/libcineform#2]
There is a lot of code cleaning in the 9 commits since the first release made on 2018-05-16.

**Comment by emericg** [comment]
Yes sure, I can make a 0.2.
Are you using the last commit without problems already?

**Comment by retokromer** [comment]
Yes, I am using 1af16fa.

**Comment by emericg** [comment]
Allright here it is https://github.com/emericg/libcineform/releases/tag/v0.2 !
Might be time to retry integrating this in VLC and GStreamer...

Fill free to ask for anything you might need, or contribute to build system improvements!

**Comment by retokromer** [comment]
Merci beaucoup!
